apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "db-operator.name" . }}
    helm.sh/chart: {{ include "db-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "db-operator.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "db-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "db-operator.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{ if (.Values.namespaces) }}
          - name: NAMESPACES
            value: {{ include "helm-toolkit.utils.joinListWithComma" .Values.namespaces }}
          - name: WATCH_NAMESPACE
            value: ""
          {{ else }}
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{ end }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: {{ .Chart.Name }}

          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "db-operator.fullname" . }}