{{- if .Values.rbac.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: "{{ include "db-operator.fullname" . }}-dbs"
rules:
    - apiGroups:
          - db.clarizen.cloud
      resources:
          - '*'
      verbs:
          - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: {{ include "db-operator.fullname" . }}
        - apiGroups:
              - ""
          resources:
              - 'pods'
              - 'configmaps'
          verbs:
              - 'get'
              - 'list'
              - 'watch'
        - apiGroups:
              - ""
          resources:
              - 'configmaps'
          verbs:
              - 'create'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: "{{ include "db-operator.fullname" . }}-secrets"
        - apiGroups:
              - ""
          resources:
              - 'secrets'
          verbs:
              - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: "{{ include "db-operator.fullname" . }}-dbs"
subjects:
    - kind: ServiceAccount
      name: {{ include "db-operator.fullname" . }}
roleRef:
    kind: ClusterRole
    name: {{ include "db-operator.fullname" . }}
    apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: "{{ include "db-operator.fullname" . }}-dbs"
    namespace: {{ .Release.Namespace }}
subjects:
    - kind: ServiceAccount
      name: {{ include "db-operator.fullname" . }}
roleRef:
    kind: ClusterRole
    name: {{ include "db-operator.fullname" . }}
    apiGroup: rbac.authorization.k8s.io

{{ range .Values.namespaces }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "db-operator.fullname" $ }}
    namespace: {{ . }}
subjects:
    - kind: ServiceAccount
      name: {{ include "db-operator.fullname" $ }}
      namespace: {{ $.Release.Namespace }}
roleRef:
    kind: ClusterRole
    name: {{- printf "%s-%s" include "db-operator.fullname" . "secrets" -}}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}