apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "db-operator.name" . }}
    helm.sh/chart: {{ include "db-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  postgres.yaml: |-
    dbUser: {{ .Values.db.user }}
    dbHost: {{ .Values.db.host }}
    dbPassword: {{ .Values.db.password }}
    dbDatabase: {{ .Values.db.database }}



