kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db-operator
subjects:
  - kind: ServiceAccount
    name: db-operator
roleRef:
  kind: ClusterRole
  name: db-operator
  apiGroup: rbac.authorization.k8s.io
