# Default values for db-operator.

replicaCount: 1

image:
  repository: vdksystem/db-operator
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

# If chart should manage permissions
rbac:
  enabled: true

db:
  user: "db_operator"
  host: "postgresql-postgresql"
  password: "use --set"
  database: "postgres"

#  Namespaces to watch
namespaces:
  - default
  - test
  - test2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
